name: Build APK Webview Murni

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Tarik Kode
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install dependencies
      run: npm install

    - name: Generate Folder Android Otomatis
      # Di sini letak keajaibannya, GitHub bakal bikin folder android di awan
      run: npx cap add android

    - name: Build APK
      working-directory: ./android
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease

    - name: Upload Hasil APK
      uses: actions/upload-artifact@v4
      with:
        name: APK-Topup-Jadi
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
